GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQm9iIiwiaWF0IjoxNTg1OTIxMzA5fQ.KUitvojy-SuKe9PkY3ShleZk0K26vA5tWeGD9J62k08

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Bob"
}